mongodb:
    image: dockerfile/mongodb
    expose: 
     -  27017
    ports:
     -  27017
    volumes:
     -  /var/mongo/db:/data/db
    restart: always
api:
    build: github.com/Softhouse/laughing-batman.git
    ports:
     - 3232:3232
    links:
     -  mongodb
    env_file: github_secret.env
    environment: 
     -  KATALOG_VHOSTS=default/api
     -  MONGO_HOST=mongodb
    restart: always
